theme: jekyll-theme-slate
title: â…lyph Custom Scripts
description: Random scripts that may be useful
avatar: "/images/glyph.jpg"
logo: /images/glyph.jpg
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
